-- 1. Create the portfolio_content table
create table if not exists portfolio_content (
  id bigint generated by default as identity primary key,
  section_name text unique not null,
  content jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable Row Level Security (RLS)
alter table portfolio_content enable row level security;

-- 3. Create policies
-- Allow everyone to read content (so the website works)
create policy "Allow public read access"
  on portfolio_content for select
  using (true);

-- Allow only authenticated users (Admin) to insert/update/delete
create policy "Allow authenticated insert"
  on portfolio_content for insert
  with check (auth.role() = 'authenticated');

create policy "Allow authenticated update"
  on portfolio_content for update
  using (auth.role() = 'authenticated');

-- 4. Insert Initial Data (from your current website)
insert into portfolio_content (section_name, content) values
(
  'hero',
  '{
    "name": "MD Zeehan Siddique",
    "subtitle": "Mechanical Engineer & CAD Designer",
    "description": "Mechanical engineering student with expertise in CAD design and problem-solving. Specialized in project management, strategic planning, and driving innovative solutions through collaborative leadership.",
    "profile_url": "assets/profile.png"
  }'::jsonb
),
(
  'education',
  '{
    "raw": "Current | B.Sc. in Mechanical Engineering | Islamic University of Technology (IUT), Dhaka | CGPA: 3.67 / 4.00\n2020 – 2022 | Higher Secondary School Certificate | Government City College, Chittagong | GPA: 5.00 / 5.00\n2014 – 2020 | Secondary School Certificate | Ispahani Public School and College, Chittagong | GPA: 5.00 / 5.00"
  }'::jsonb
),
(
  'experience',
  '{
    "raw": "June 2025 – Present | Co-Founder & Treasurer | Short Circuit, Dhaka | Manage inventory systems and collaborate with suppliers to maintain optimal stock levels.; Oversee financial transactions ensuring accuracy, transparency, and compliance with standards.\nInternship | Mechanical Intern | GPH Ispat Ltd., Chittagong | Exposure to core mechanical processes in steel manufacturing and material handling systems.; Studied operation of rolling mills, furnaces, and industrial control instruments.; Assisted in routine inspections, maintenance, and plant safety procedures."
  }'::jsonb
),
(
  'activities',
  '{
    "raw": "Vice-Chairperson | IMechE IUT Student Chapter | Organized key events like SofE and RoboKick Rumble; managing core club activities.\nSenior Mechanical Team Member | Project Altair (IUT Mars Rover Team) | Competed in European Rover Challenge 2024, IRDC 2025, and IRC 2026. Secured 18th place globally in URC.\nExecutive Member | IUT Automobile Society (AUS) & Photography Society (IUTPS) | Organizer for Automech, one of the largest national automobile festivals."
  }'::jsonb
),
(
  'skills_awards',
  '{
    "skills": "SolidWorks, Microsoft Excel, Project Management, Inventory Management, Financial Record Keeping, Content Creation",
    "awards": "CSWA Certification for SolidWorks {assets/cswa.png}\nUniversity Rover Challenge 2025 (The Mars Society) {assets/urc_2025.jpg}\nAUST Rover Challenge 2.0 (ARC 2.0) Award {assets/arc_2_0.png}\nThe Duke of Edinburgh Award (Bronze & Silver)\nHSC Scholarship for Academic Excellence"
  }'::jsonb
),
(
  'contact',
  '{
    "phone": "+8801746507888",
    "email": "zeehansiddique9@gmail.com",
    "linkedin": "https://linkedin.com/in/zeehansiddique"
  }'::jsonb
),
(
  'settings',
  '{
    "theme": "default"
  }'::jsonb
)
on conflict (section_name) do nothing;
